---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - name: app-flask
          image: shipyarr/app-flask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6061
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-flask
spec:
  selector:
    app: app-flask
  ports:
    - protocol: TCP
      port: 6061
      targetPort: 6061
  type: LoadBalancer
