---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-flask
  template:
    metadata:
      labels:
        app: app-flask
    spec:
      containers:
        - name: app-flask
          image: shipyarr/app-flask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6061
              name: http
          resources:
            limits:
              cpu: "1"
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: app-flask
spec:
  selector:
    app: app-flask
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-flask
spec:
  ingressClassName: nginx
  rules:
  - host: app-flask.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-flask
            port:
              name: http
