---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-gin
  template:
    metadata:
      labels:
        app: app-gin
    spec:
      containers:
        - name: app-gin
          image: shipyarr/app-gin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6060
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-gin
spec:
  selector:
    app: app-gin
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  type: LoadBalancer
