---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-gin
  template:
    metadata:
      labels:
        app: app-gin
    spec:
      containers:
        - name: app-gin
          image: shipyarr/app-gin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6060
              name: http
          resources:
            limits:
              cpu: "1"
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: app-gin
spec:
  selector:
    app: app-gin
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-gin
spec:
  ingressClassName: nginx
  rules:
  - host: app-gin.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-gin
            port:
              name: http
